let l = 0; // <= 변하는 변수 값 변경가능
const c = 0; // <= 절대로 변하지 않는 값 변경 불가능

let ame = "남진우"; // String
let age = 17; // Number
let boll = true; // boolean
let n = null; // null
let ud = undefined; // undefined (정의되지않은)

console.log(ame, age, boll, n ,ud)

let calssname = "이원준";
let classNumber = 13;
const year = 2008;

console.log("이름은: " + calssname)
console.log("번호는: " + classNumber)
console.log("태어난 년도는: " + year)